services:
    some-redmine:
        image: redmine
        networks:
        - some-network
        ports:
        - 8000:3000
        environment:
        - REDMINE_DB_POSTGRES=some-postgres
        - REDMINE_DB_USERNAME=redmine
        - REDMINE_DB_PASSWORD=secret
        volumes:
        - redmine-files:/usr/src/redmine/files
        - redmine-plugins:/usr/src/redmine/plugins
    some-postgres:
        image: postgres
        networks:
        - some-network
        environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=redmine
        volumes:
        - postgres-data:/var/lib/postgresql/data
networks:
    some-network:
volumes:
    redmine-files:
    redmine-plugins:
    postgres-data:
        
        
